language: scala

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

jdk:
  - openjdk8

script:
  ## This runs the template with the default parameters, and runs test within the templated app.
  - sbt -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M test

  - pushd target/sbt-test/scala3-tasty-inspector-template/scripted
  - sbt inspector/run test
  - popd

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
